
import java.io.*;
import java.util.Scanner;

public class AriannasAppliances {

    public static void main(String[] args) throws IOException {
        double totalRevenue = 0;
        Scanner keyboard = new Scanner(System.in);
        int Dishwashers, Washers, Dryers, Refrigerators, Ovens,
                dishwasherSales = 0, washerSales = 0, dryerSales = 0, refrigeratorSales = 0, ovenSales = 0;
        System.out.println(CenteredString("***** Ariannas Appliances 2024 *****", 50));
        System.out.println("This Program will determine the annual sales revenue for Ariannas" + "\nAppliances\n");
        System.out.println("It will report the sales revenue for each appliance, percentage of total\n" + "revenues generated by each appliance, and the total sales revenues for " + "\n2024\n");

        PrintWriter outputFile = new PrintWriter("Revenues.txt");

        for (int Quarter = 0; Quarter < 4; Quarter++) {
            System.out.print("Enter the Sales for 2024 Quarter " + (Quarter + 1));

            System.out.print("\nDishwasher: ");
            Dishwashers = keyboard.nextInt();

            System.out.print("Washer: ");
            Washers = keyboard.nextInt();
            
            System.out.print("Dryers: ");
            Dryers = keyboard.nextInt();
            
            System.out.print("Refrigerators: ");
            Refrigerators = keyboard.nextInt();
            
            System.out.print("Ovens: ");
            Ovens = keyboard.nextInt();

            dishwasherSales += Dishwashers;
            washerSales += Washers;
            dryerSales += Dryers;
            refrigeratorSales += Refrigerators;
            ovenSales += Ovens;
            outputFile.printf("%d  %d  %d  %d  %d%n", Dishwashers, Washers, Dryers, Refrigerators, Ovens);
        }

        outputFile.close();
        keyboard.close();

        Scanner fileScanner = new Scanner(new File("Revenues.txt"));
        while (fileScanner.hasNext()) {
            int dishwasher = fileScanner.nextInt();
            int washer = fileScanner.nextInt();
            int dryer = fileScanner.nextInt();
            int refrigerator = fileScanner.nextInt();
            int oven = fileScanner.nextInt();

            totalRevenue += dishwasher + washer + dryer + refrigerator + oven;
        }
        fileScanner.close();

        double dishwasherPercent, washerPercent, refrigeratorPercent, dryerPercent, ovenPercent;
        dishwasherPercent = (dishwasherSales / totalRevenue) * 100;
        washerPercent = (washerSales / totalRevenue) * 100;
        refrigeratorPercent = (refrigeratorSales / totalRevenue) * 100;
        dryerPercent = (dryerSales / totalRevenue) * 100;
        ovenPercent = (ovenSales / totalRevenue) * 100;

        System.out.println(CenteredString("***** Ariannas Appliances 2024 *****", 40) + "\n");
        System.out.println(("Dishwasher Revenues") + CenteredString(String.format("$ %d (%.1f%%)", dishwasherSales, dishwasherPercent), 40));
        System.out.println(("Washer Revenues") + CenteredString(String.format("$ %d (%.1f%%)", washerSales, washerPercent), 48));
        System.out.println(("Refrigerator Revenues") + CenteredString(String.format("$ %d (%.1f%%)", refrigeratorSales, refrigeratorPercent), 35));
        System.out.println(("Dryer Revenues") + (CenteredString(String.format("$ %d (%.1f%%)", dryerSales, dryerPercent), 50)));
        System.out.println(("Oven Revenues") + CenteredString(String.format("$ %d (%.1f%%)", ovenSales, ovenPercent), 51));
        System.out.println(CenteredString("===============", 77));
        System.out.println(("Total Sales Revenues for 2024") + CenteredString(String.format("$ %.2f", totalRevenue), 15));
    }

    public static String CenteredString(String string, int columnWidth) {

        int padding;

        padding = (columnWidth - string.length()) / 2;

        padding = padding <= 0 ? 0 : padding;

        int stringLength = string.length();

        return String.format("%" + (padding + stringLength) + "s", string);
    }
}
